apiVersion: v1
description: A Helm chart for Shipment Service
name: shipmentservice
version: 0.1.1
sources:
- https://dxdevop.visualstudio.com/mrpmicro/_git/code
maintainers:
- name: David
  email: david.tesar@microsoft.com
engine: gotpl
